name: Build and Deploy to AWS

on:
  # push:
    # branches: [main]
  workflow_dispatch:

permissions:
  id-token: write
  contents: write

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-9

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # OIDC AWS creds
      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::012889719104:role/oidc_role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t flask-app:latest .
          docker tag flask-app:latest ${{ steps.login-ecr.outputs.registry }}/flask-app:cicd

      - name: Push Docker image to ECR
        run: |
          docker push ${{ steps.login-ecr.outputs.registry }}/flask-app:latest

 
