name: Image Resizing using Lambda Function

on:
 workflow_dispatch:
  #push:
    # paths:
    #   - 'usecase-5/**'
    #   - '.github/workflows/deploy_uc5.yml'
    # branches: main
  
permissions:
  id-token: write
  contents: write

jobs:
  terraform-uc5:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-5

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
      
      - name: SetUp AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Create terraform.tfvars
        run: |
          cat <<EOF > terraform.tfvars
          sns_topic_name = "s3-sns-topic"
          bucket_input_name = "non-resized-image-pranjal-72312"
          bucket_output_name = "resized-image-pranjal-72312"
          lambda_s3_bucket = "pranjal71025"
          lambda_s3_key = "lambda.zip"
          lambda_name = "image-resize-lambda-function"
          email = "pranjal.deka@hcltech.com"
          lambda_role = "arn:aws:iam::836837432401:role/service-role/image-resize-lambda-function-role-68p530eb"
          EOF

    
      - name: Run implement terraform
        run: |
          terraform init
          terraform fmt -recursive
          terraform validate
          terraform plan -var-file=terraform.tfvars
          terraform apply -var-file=terraform.tfvars -auto-approve

          
