name: ECS API - usecase10

on:
 workflow_dispatch:
  
permissions:
  id-token: write
  contents: write

jobs:
  ECS-API-uc-10:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-10

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE }}
      # - name: Set up TFLint
      #   uses: terraform-linters/setup-tflint@v4
      #   with:
      #     tflint_version: latest

      # - name: Initialize TFLint
      #   run: tflint --init

      # - name: Run TFLint
      #   run: tflint -f compact
      #   continue-on-error: true
        
      # - name: Run TFLint
      #   #run: tflint -f compact
      #   run: tflint --format default

      # - name: Setup Python for Checkov
      #   uses: actions/setup-python@v5.6.0

      # - name: Install Checkov
      #   run: pip install checkov

      # - name: Run Checkon Scan
      #   run: checkov -d . --framework terraform --soft-fail --output json > checkov_output.json

      # - name: Upload build artifact
      #   uses: actions/upload-artifact@v4.6.2
      #   with:
      #    name: checkov-info
      #    path: checkov_output.json

      # - name: Install Conftest (OPA)
      #   run: |
      #     wget https://github.com/open-policy-agent/conftest/releases/download/v0.45.0/conftest_0.45.0_Linux_x86_64.tar.gz
      #     tar xzf conftest_0.45.0_Linux_x86_64.tar.gz
      #     sudo mv conftest /usr/local/bin
      #     rm -f conftest_0.45.0_Linux_x86_64.tar.gz

      # - name: Run OPA Policy Check with Conftest
      #   run: |
      #     terraform plan -out tfplan.binary
      #     terraform show -json tfplan.binary > tfplan.json
      #     conftest test tfplan.json -p policy
      #   continue-on-error: true
        

      - name: Run implement terraform
        run: |
          terraform init -reconfigure
          # terraform test
          # terraform fmt -recursive
          #terraform validate
          terraform plan -var-file=terraform.tfvars
          #terraform apply -var-file=terraform.tfvars -auto-approve
         #terraform destroy -var-file=terraform.tfvars -auto-approve
