name: ECS_ALB_API_GATEWAY

on:
 workflow_dispatch:
  
permissions:
  id-token: write
  contents: write

jobs:
  ECS-fargate:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ECS_ALB_API_GATEWAY

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE }}
 

      - name: Run implement terraform
        run: |
          terraform init -reconfigure
          #terraform test
          #terraform fmt -recursive
          #terraform validate
          terraform plan -var-file=terraform.tfvars
          #terraform apply -var-file=terraform.tfvars -auto-approve
          #terraform destroy -var-file=terraform.tfvars -auto-approve
