name: Automation using Terraform

on:
 workflow_dispatch:

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: UC2
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: us-east-1

      # TFLint Setup and Run
      - name: Set up TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
      - name: Initialize TFLint
        run: tflint --init
        

      - name: Run TFLint
        run: tflint -f compact
        
      - name: Terraform Init
        run: terraform init
        
      
      - name: Terraform Syntax Checking
        run: terraform fmt
        
      - name: Terraform Code Validation
        run: terraform validate
        

      - name: Terraform Plan
        run: terraform plan
        

      - name: Terraform Apply
        run: terraform apply -auto-approve
       
