name: OPA Policy Check

on:
  push:
    branches: [main]

jobs:
  opa-policy-check:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install OPA
      run: |
        curl -L -o opa https://openpolicyagent.org/downloads/latest/opa_linux_amd64_static
        chmod +x opa
        sudo mv opa /usr/local/bin/

    - name: Run OPA policy
      run: |
        mkdir -p reports
        opa eval --format=json --input input.json --data policy.rego "data.github.deny" > reports/opa-report.json

    - name: Upload OPA report
      uses: actions/upload-artifact@v4
      with:
        name: opa-report
        path: reports/opa-report.json
