name: EC2 start and stop

on:
 workflow_dispatch:
  
permissions:
  id-token: write
  contents: write

jobs:
  terraform-uc6-ec2:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-6

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS OIDC
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.OIDC_ROLE }}
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: latest
          
      - name: Show version
        run: tflint --version

      - name: Init TFLint
        run: tflint --init
        
      # - name: Run TFLint
      #   #run: tflint -f compact
      #   run: tflint --format default

      - name: Setup Python for Checkov
        uses: actions/setup-python@v5.6.0

      - name: Install Checkov
        run: pip install checkov

      - name: Run Checkon Scan
        run: checkov -d . --framework terraform --soft-fail --output json > checkov_output.json

      - name: Upload build artifact
        uses: actions/upload-artifact@v4.6.2
        with:
         name: checkov-info
         path: checkov_result.json
        

      - name: Run implement terraform
        run: |
          terraform init
          #terraform fmt -recursive
          # terraform validate
          # terraform plan -var-file=terraform.tfvars
          # terraform apply -var-file=terraform.tfvars -auto-approve
          # terraform destroy -var-file=terraform.tfvars -auto-approve
