name: EC2 start and stop

on:
 workflow_dispatch:
  
permissions:
  id-token: write
  contents: write

jobs:
  terraform-uc6:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: usecase-6

    steps:
      - name: Code checkout
        uses: actions/checkout@v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: SetUp AWS
        uses: aws-actions/configure-aws-credentials@v4.1.0
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}


      - name: Run implement terraform
        run: |
          terraform init
          #terraform fmt -recursive
          # terraform validate
          terraform plan -var-file=terraform.tfvars
          terraform apply -var-file=terraform.tfvars -auto-approve
          # terraform destroy -var-file=terraform.tfvars -auto-approve
